# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(432, 220))
        MainWindow.setMaximumSize(QtCore.QSize(432, 220))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ln_display = QtWidgets.QLineEdit(self.centralwidget)
        self.ln_display.setGeometry(QtCore.QRect(56, 6, 321, 33))
        self.ln_display.setStyleSheet("font: 75 12pt \"PLRoman10\";")
        self.ln_display.setText("")
        self.ln_display.setReadOnly(True)
        self.ln_display.setObjectName("ln_display")
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setGeometry(QtCore.QRect(342, 179, 84, 35))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_1x = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1x.setGeometry(QtCore.QRect(342, 39, 84, 35))
        self.btn_1x.setObjectName("btn_1x")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(6, 39, 84, 35))
        self.btn_clear.setObjectName("btn_clear")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(342, 74, 84, 35))
        self.btn_div.setObjectName("btn_div")
        self.btn_x3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_x3.setGeometry(QtCore.QRect(174, 39, 84, 35))
        self.btn_x3.setObjectName("btn_x3")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(90, 179, 84, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setIconSize(QtCore.QSize(16, 16))
        self.btn_1.setObjectName("btn_1")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(258, 179, 84, 35))
        self.btn_3.setObjectName("btn_3")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(258, 74, 84, 35))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_soma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_soma.setGeometry(QtCore.QRect(90, 74, 84, 35))
        self.btn_soma.setObjectName("btn_soma")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(342, 109, 84, 35))
        self.btn_0.setObjectName("btn_0")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(258, 144, 84, 35))
        self.btn_6.setObjectName("btn_6")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(174, 179, 84, 35))
        self.btn_2.setObjectName("btn_2")
        self.btn_sin = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sin.setGeometry(QtCore.QRect(6, 74, 84, 35))
        self.btn_sin.setObjectName("btn_sin")
        self.btn_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sqrt.setGeometry(QtCore.QRect(258, 39, 84, 35))
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(258, 109, 84, 35))
        self.btn_9.setObjectName("btn_9")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(174, 109, 84, 35))
        self.btn_8.setObjectName("btn_8")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(174, 74, 84, 35))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(90, 144, 84, 35))
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(174, 144, 84, 35))
        self.btn_5.setObjectName("btn_5")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(90, 109, 84, 35))
        self.btn_7.setObjectName("btn_7")
        self.btn_tg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tg.setGeometry(QtCore.QRect(6, 144, 84, 35))
        self.btn_tg.setObjectName("btn_tg")
        self.btn_1tg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1tg.setGeometry(QtCore.QRect(6, 179, 84, 35))
        self.btn_1tg.setMaximumSize(QtCore.QSize(84, 35))
        self.btn_1tg.setObjectName("btn_1tg")
        self.btn_x2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_x2.setGeometry(QtCore.QRect(90, 39, 84, 35))
        self.btn_x2.setObjectName("btn_x2")
        self.btn_dot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dot.setGeometry(QtCore.QRect(342, 144, 84, 35))
        self.btn_dot.setObjectName("btn_dot")
        self.btn_cos = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cos.setGeometry(QtCore.QRect(6, 109, 84, 35))
        self.btn_cos.setObjectName("btn_cos")
        self.ln_display.raise_()
        self.btn_1x.raise_()
        self.btn_ok.raise_()
        self.btn_div.raise_()
        self.btn_x3.raise_()
        self.btn_1.raise_()
        self.btn_3.raise_()
        self.btn_mult.raise_()
        self.btn_soma.raise_()
        self.btn_0.raise_()
        self.btn_6.raise_()
        self.btn_2.raise_()
        self.btn_sin.raise_()
        self.btn_sqrt.raise_()
        self.btn_9.raise_()
        self.btn_8.raise_()
        self.btn_sub.raise_()
        self.btn_4.raise_()
        self.btn_5.raise_()
        self.btn_7.raise_()
        self.btn_tg.raise_()
        self.btn_1tg.raise_()
        self.btn_x2.raise_()
        self.btn_dot.raise_()
        self.btn_cos.raise_()
        self.btn_ok.raise_()
        self.btn_1x.raise_()
        self.btn_clear.raise_()
        self.btn_div.raise_()
        self.btn_x3.raise_()
        self.btn_1.raise_()
        self.btn_3.raise_()
        self.btn_mult.raise_()
        self.btn_soma.raise_()
        self.btn_0.raise_()
        self.btn_6.raise_()
        self.btn_2.raise_()
        self.btn_sin.raise_()
        self.btn_sqrt.raise_()
        self.btn_9.raise_()
        self.btn_8.raise_()
        self.btn_sub.raise_()
        self.btn_4.raise_()
        self.btn_5.raise_()
        self.btn_7.raise_()
        self.btn_tg.raise_()
        self.btn_1tg.raise_()
        self.btn_x2.raise_()
        self.btn_dot.raise_()
        self.btn_cos.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nub Calculator"))
        self.btn_ok.setText(_translate("MainWindow", "OK"))
        self.btn_1x.setText(_translate("MainWindow", "1/x"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_x3.setText(_translate("MainWindow", "x³"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_soma.setText(_translate("MainWindow", "+"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_sin.setText(_translate("MainWindow", "sin"))
        self.btn_sqrt.setText(_translate("MainWindow", "Sqrt"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_tg.setText(_translate("MainWindow", "tg"))
        self.btn_1tg.setText(_translate("MainWindow", "1/tg"))
        self.btn_x2.setText(_translate("MainWindow", "x²"))
        self.btn_dot.setText(_translate("MainWindow", "."))
        self.btn_cos.setText(_translate("MainWindow", "cos"))
